[green_agent]
endpoint = "http://127.0.0.1:9009"
cmd = "python scenarios/debate/debate_judge.py --host 127.0.0.1 --port 9009"

[[participants]]
role = "pro_debater"
endpoint = "http://127.0.0.1:9019"
cmd = "python scenarios/debate/debater.py --host 127.0.0.1 --port 9019"

[[participants]]
role = "con_debater"
endpoint = "http://127.0.0.1:9018"
cmd = "python scenarios/debate/debater.py --host 127.0.0.1 --port 9018"

[config]
topic = "Should artificial intelligence be regulated?"
num_rounds = 3
